### ISSUE TITLE
Sway Logout support

### ISSUE THREAD

**Issue by BowlBird** [lighttigerXIV/ulauncher-session-manager#2]
Currently this extension supports GNOME and KDE as desktop environments for logging out. Sway support shouldn't be too difficult as the command 
```bash
swaymsg exit
``` 
should exit the environment. Thanks!

**Comment by lighttigerXIV** [comment]
Sure i will do something tomorrow

**Comment by BowlBird** [comment]
I did submit a pull request if you want to look into it, I tested it on my sway install and it works. :)

**Comment by lighttigerXIV** [comment]
> I did submit a pull request if you want to look into it, I tested it on my sway install and it works. :)

I don't know if you noticed it but I added it last week. I will close this issue now
